### ISSUE TITLE
Conversions around OPEX Fixed Specific variable

### ISSUE THREAD

**Issue by clarabachorz** [PhilippVerpoort/posted#14]
Two bugs found with the calculation and conversion of `OPEX Fixed Specific`:
- Conversion using OCF uses the wrong units: an OCF reported in units of % (eg 91.3%), is interpreted as 91.3, rather than 0.913. This issue affects the `Cement with CC` file for example, where all OPEX are reported as `OPEX Variable` to avoid this conversion error.
- Unit conversions that use heating values: this bug was found in the `Methanol Synthesis with Reforming` file. The Methanol Output is given in tons, whereas the reference flow has to be in MWh. 
As a result, `unit_convert` changes this to MWh;LHV, but then raises an error: the reference unit reported goes from 't/a' to 'MWh;LHV/a', which `unit_convert` finds to be a `variant`, but splits into 'MWh' and 'LHV/a'. It then doesn't recognize LHV/a as a unit, obviously. 
So there is a bug somewhere about where this '/a' is appended, the unit should have been converted from 't/a' to 'MWh/a;LHV'

**Comment by PhilippVerpoort** [comment]
Thanks for reporting those issues.

* I just pushed commit https://github.com/PhilippVerpoort/posted/commit/e761c3fbd52ee4504857396c0307153a8514971d, which fixes this issue. Please feel free to revert the entries in `Cement Production` back to `OPEX Fixed Specific` and test if it works.

* I think this was not a code issue but rather a data issue. The `Output Capacity` was reported in units of `metric_tonne` rather than `metric_tonne/a`. As a consequence, posted tries to convert `metric_tonne` to `MWh/a` and obviously fails, because one is of dimensionality `[flow]` and the other of `[flow]/[time]`. I debugged `DataSet('Tech|Methanol Synthesis with Reforming').normalise()` and found that it calls `unit_convert('metric_ton', 'MWh/a;LHV', 'Methanol')`, which should raise that exception. I'm noticing that the TEDF checks don't pick this up though (e.g. when running `TEDF('Tech|Methanol Synthesis with Reforming').load().check()`). This is something we can revisit later when we're improving the TEDF checks and creating automated tests. However it seems as if you already fixed this in your commit https://github.com/clarabachorz/posted/commit/345d766513f5933a8749433ebb588b83cc03b783.
